name: Node CI

on:
  push:
    branches:
      - header

defaults:
  run:
    shell: bash

jobs:
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [18, 20]
#    steps:
#      - uses: actions/checkout@v4
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v4
#        with:
#          node-version: ${{ matrix.node-version }}
#      - run: npm ci
#      - run: npm test

  tests_e2e:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Start server and check login
        run: bash ./run-app.sh
      - name: Run grid
        run: docker compose up -d
      - name: Run tests
        run: SELENIUM_REMOTE_URL=http://host.docker.internal:4444 npx playwright test